[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Chromite"
dynamic = ["version"]
description = "Chromite is a framework for text and ASCI formatting in Python."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "NastyaNoTamashii" }
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Communications :: Chat",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[project.urls]
"Documentation (GitHub)" = "https://github.com/NastyaNoTamashii/Chromite/blob/main/README.md"
"Source (GitHub)" = "https://github.com/NastyaNoTamashii/Chromite"

[tool.hatch.version]
path = "Chromite/__init__.py"